services:
  app:
    container_name: nestjs-skeleton
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/usr/src/app/src