version: '3.4'

services:
  app:
    container_name: nestjs-skeleton
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - ${PORT}:${PORT}